tinode/chat

INSTALL.md
Hello, Gene
Here is the PR for Hangup Signal issue (https://github.com/tinode/chat/issues/25). Let me know your opinion.
Thanks
=> [Add SIGHUP Caution to INSTALL.MD]

server/hub.go
Hello, Gene
When I hit Tinode with high traffic, I got following errors: 
- `fatal error: concurrent map read and map write`
- `fatal error: concurrent map writes`
The cause of these errors is because there is a race condition on `hub.topics`. So to fix this issue I suggest we use `sync.RWMutex` to synchronize read & write operations to the map. 
Thanks
=> [Attempt to Fix `hub.topics` Race Condition]

docker/tinode/entrypoint.sh
=> Fixing bug with checking if DB is reset

chatbot/csharp/Tinode.ChatBot.DemoNet46/Program.cs, chatbot/csharp/Tinode.ChatBot.DemoNet46/Properties/AssemblyInfo.cs, chatbot/csharp/Tinode.ChatBot.DemoNetCore/Program.cs, chatbot/csharp/Tinode.ChatBot.DemoNetCore/Tinode.ChatBot.DemoNetCore.csproj, chatbot/csharp/Tinode.ChatBot/ChatBot.cs, chatbot/csharp/Tinode.ChatBot/Tinode.ChatBot.csproj
ChangeLogs:
1. Add message  event notify, such as ServerPresEvent,ServerMetaEvent,CtrlMessageEvent,ServerDataEvent;
2. Add Subscriber for subscriber list;
3 Fixed no avatar meta data null reference exception;
I published the ChaBot .net library to [nuget.org](https://www.nuget.org/packages/Tinode.ChatBot/)
=> Add new features and bug fixed, also published to nuget [Tinode.ChatBot]

server/db/mysql/adapter.go
I reappear the problem, and I fixed it.
=> fix for tinode#188

server/cluster.go, server/hub.go
This is not a full solution. Pres messages are still not propagated
to new sessions.
=> Pres message routing in cluster mode. Part 1.

server/cluster.go
The field maps to ServerComMessage.Pres.wantReply.
The latter isn't tagged and, hence, doesn't get serialized and sent
as a part of the RPC payload.
=> PresWantReply field in ClusterReq.

docker/README.md, docker/tinode/entrypoint.sh, docs/faq.md
More flexibility in running tinode docker container.
=> Route pres cluster

server/cluster.go, server/cluster_leader.go, server/pres.go, server/session.go, server/sessionstore.go
=> Revert "Send {pres term} to displaced topic subs"

server/cluster.go, server/cluster_leader.go, server/pres.go, server/session.go, server/sessionstore.go
I've updated the comments. Let's agree on the data structure and I'll make appropriate changes in this PR.
=> {pres term} on rehashing to displaced topics (attempt 2).

server/db/adapter.go
arg names according to implementation in **mysql/adapter.go** and **rethinkdb/adapter.go**
=> just a few typos

server/db/adapter.go, server/db/mysql/adapter.go, server/db/rethinkdb/adapter.go, server/store/store.go
* Removed unused `name `parameter from `store.RegisterAdapter`
* Removed redundant type conversion in `adapter.Open`
=> Refactoring

server/cluster.go
This is a bit extreme but missing remote subscription is a bug. Crash should allow us to catch it if it ever happens.
=> Try to catch cases when remote subscription is missing

docs/API.md
=> Word correction in API doc

docs/API.md
=> Word correction in API doc 2

docs/monitoring.md
Fixed mistake in the parameter name (`LiveTopics`)
=> Word correction

server/db/mongodb/adapter.go
=> make replica_set optional

server/hub.go, server/init_topic.go, server/pres.go, server/topic.go
=> Fix for missing presence notifications

server/db/mongodb/adapter.go
**before** param should have been exclusive. Fixed.
=> fixed "before" param was inclusive.

server/db/mongodb/adapter.go, server/db/mongodb/schema.md
=> Ability to suspend users (MongoDB)

server/db/mongodb/tests/mongo_test.go
=> cleanup: unused err assignments

docker/tinode/config.template, server/push/fcm/push_fcm.go, server/push/push.go, server/tinode.conf, server/topic.go, tn-cli/README.md, tn-cli/tn-cli.py
Also AndroidNotification refactored. This refactoring is not directly related to the new push type.
=> Pushes for new subscriptions

server/db/mysql/adapter.go
Discovered these while implementing macros in tn-cli.
=> Fix a couple of errors in MySQL adapter.

tn-cli/README.md, tn-cli/macros.py, tn-cli/sample-macro-script.txt, tn-cli/tn-cli.py, tn-cli/tn_globals.py
Macros are high-level commands that expand to a sequence of
basic Tinode CLI commands.
=> Add macro functionality to tn-cli.

server/auth/anon/auth_anon.go, server/auth/auth.go, server/auth/basic/auth_basic.go, server/auth/rest/auth_rest.go, server/auth/token/auth_token.go, server/session.go, server/templ/email-password-reset.templ, server/validate/email/validate.go, server/validate/tel/validate.go, server/validate/validator.go
Login is included in the password reset email message.
=> Add login to Validator.ResetSecret signature.

server/main.go, server/push/fcm/payload.go, server/push/fcm/push_fcm.go, server/push/tnpg/push_tnpg.go
Something simple to start with.
I'll add sending all payloads in one request and compression in a followup PR.
=> Basic Tinode Push Gateway adapter.

server/push/tnpg/push_tnpg.go
Also, send pushes to `pushgw.tinode.co/push` by default.
=> TNPG: push all messages in one request and compress request payloads.

docker/tinode/Dockerfile, docker/tinode/config.template, docker/tinode/entrypoint.sh, monitoring/exporter/main.go
As a part of preparing docker-compose setup.
=> Tinode docker consolidation.

docker/e2e/README.md, docker/e2e/cluster-docker-compose.yml, docker/e2e/standalone-docker-compose.yml
Docker-compose configuration for standalone and cluster setups.
=> Example end-to-end setups

server/cluster.go
The previous change fixed the cases when the topic was deleted. It did not fix the most common use case of unsubscribing from all topics.
=> Another attempt at fixing memory leak

server/datamodel.go, server/hub.go, server/session.go, server/topic.go
This PR is purposed to establish a general pattern to override session param.
=> Basic session param override struct

server/cluster.go, server/datamodel.go, server/hub.go, server/init_topic.go, server/session.go, server/topic.go
=> Topic proxy: basic routing between proxy and master.

server/cluster.go, server/hub.go, server/session.go, server/topic.go
This PR adds basic functionality for routing meta messages and broadcasting responses to proxied sessions.
=> Topic Proxy: Route meta messages and broadcast responses.

server/cluster.go, server/cluster_leader.go, server/hub.go, server/pres.go, server/topic.go
Also, a couple of minor fixes and changes to presence notifications handling.
=> Invalidate proxied subs on cluster rehash.

server/cluster.go, server/topic.go
Set meta.{set,get} topic proxy params.
Use session overrides in pres notifications.
=> A couple of fixes in topic proxy meta request processing

server/cluster.go, server/pres.go, server/store/types/types.go, server/topic.go
I think this was missing from your PR yesterday.
P.S. your push notifications still don't work.
Also `go fmt`.
=> Don't update pud if acs is invalid

server/push/fcm/payload.go
=> fix click_action in fcm messages for android

server/db/mongodb/adapter.go, server/tinode.conf
=> mongo adapter tls support

server/cluster.go, server/sessionstore.go, server/user.go
When the user is deleted, all user's sessions must be terminated on all nodes.
=> Broadcast eviction to all nodes when user is deleted

server/hub.go, server/session.go
Fix bug on topicsStateForUser
Fix bug cannot delete topic
=> Fix minor bugs

loadtest/tsung.xml
Publish to all user topics in the load test config.
=> Add a bit of functionality to loadtest

monitoring/exporter/prom_exporter.go, server/hdl_files.go, server/hdl_grpc.go, server/hdl_longpoll.go, server/hdl_websock.go, server/hub.go, server/sessionstore.go
These are helpful in measuring performance.
=> Add counters for incoming and outgoing messages.

docs/API.md, server/db/mongodb/adapter.go, server/db/mysql/adapter.go, server/db/rethinkdb/adapter.go, server/db/rethinkdb/schema.md, server/init_topic.go, server/session.go, server/store/types/types.go, server/topic.go
It's ~40% complete. Webapp from the https://github.com/tinode/webapp/tree/next branch can be used to test it.
=> Channel-related functionality

server/datamodel.go, server/pres.go, server/push/fcm/payload.go, server/push/fcm/push_fcm.go, server/push/push.go, server/push/tnpg/push_tnpg.go, server/topic.go
Added support for fcm push topics to send channel notifications.
Also a couple of bugs fixed.
=> Support for fcm push topics

monitoring/exporter/prom_exporter.go, monitoring/exporter/scraper.go, server/stats.go
Next step: add influxdb support.
=> Export latency, response size and #goroutines to Prometheus.

monitoring/exporter/prom_exporter.go, server/hub.go, server/session.go
As CtrlCodesTotal?xx variables.
=> Export response code counters.

server/cluster.go
I think this should work, another lock is not needed. What do you think?
=> fix for #524

docs/API.md, go.sum, server/hub.go, server/store/types/types.go, server/topic.go
This is probably the last PR next -> channel. I'll merge channel into devel afterwards.
Things look functional with no obvious bugs. Channels can be tested with webapp from 'next'.
=> Fixed channel permissions and disabled deleting messages in channels.

server/topic_proxy.go
It should help https://github.com/tinode/chat/issues/529
=> Always kill proxy topic when it has no more sessions.

server/run-cluster.sh, server/sanity-test.sh
0. Bring up a mysql docker container.
1. Run a simple 3-node cluster.
2. Send some requests with tn-cli.
=> Add a basic sanity test for cluster setup.

server/cluster.go, server/session.go, server/topic.go
Remove manual scheduling.
This is a draft version of it. Please, take a look and let me know what you think.
=> Run clusterWriteLoop on the master topic level.

server/session.go
Usecase:
Android client logged in, attached to `me` but not attached to, say, a p2p topic.
The peer sends a message.
The client receives a `pres msg` notification, initiates a fetch from the server and detaches from the p2p topic.
Upon receiving the corresponding `data` message, the client will send a `note recv` to the server acknowledging the message.
Currently, the `note recv` causes a noncritical server error since the Android client's session isn't attached to the p2p topic.
This logic also causes the Android client not to send `note recv` for the message when the user actually opens the p2p topic.
=> Attempt to route note.recv when session isn't attached to topic.

server/cluster.go, server/concurrency/simplemutex.go, server/topic.go
server/sanity-test.sh passes as well as a quick loadtest didn't create any trouble.
=> Make accessing Topic.{proxiedSessions,proxiedChannels} thread-safe.

server/cluster.go, server/session.go, server/sessionstore.go, server/user.go
Something that shows up when running under tsan.
=> Fix some data races.

server/cluster.go, server/cluster_leader.go, server/session.go, server/topic.go
Oddly enough, tsan reported a few more.
=> Fix a few more races.

server/tinode.conf, server/validate/email/validate.go
Fix `localhost` problem in HELO/EHLO smtp command.
Replcaed `SendMail` func with a new self defined func.
=> Fix localhost problen in HELO/EHLO command

server/topic.go
Presently, session attached to a topic that fail to handle a broadcast
(`queueOut()` returns `false`) are detached from the topic by
sending a leave request to the topic's `unreg` channel.
This (a) incurs using a synchronization primitive and (b) may result
in dropped leave requests (if the `unreg` queue becomes full).
Change the logic to detach all "bad" sessions immediately, without
routing the leave request via the `unreg` channel.
=> Detach sessions immediatelly in topic broadcast logic.

chatbot/python/chatbot.py
```bash
$ python chatbot.py --login-token=asdasd
2021-01-19 10:58:33.114 Tino, Tinode's chatbot.
Traceback (most recent call last):
File "chatbot.py", line 413, in <module>
run(args)
File "chatbot.py", line 342, in run
secret = args.login_token.encode('acsii')
LookupError: unknown encoding: acsii
```
=> chatbot: fix token encoding

docker/README.md
fix the table layout of environment variables
=> Update README.md of docker-specific instructions

server/db/adapter.go, server/db/common/common.go, server/db/common/common_test.go, server/db/mongodb/adapter.go, server/db/mongodb/tests/mongo_test.go, server/db/mongodb/tests/test_data.go, server/db/mysql/adapter.go, server/db/rethinkdb/adapter.go
* Fixed a few minor issues in TopicsForUser in MySQL.
* Updated TopicsForUser in RethinkDB to use the same logic as MySQL
* Moved common code to a separate package
* Added tests
Mongo is going to be next.
Update: added mongo, fixed some bugs, updated mongo tests.
=> Updated TopicsForUser in rethinkdb, refactored common code, added tests

server/tinode.conf, server/validate/email/validate.go
We are adding this to use Office 365 account for notifications
=> Adding support for multiple smtp auth mechanism

server/db/mongodb/adapter.go, server/tinode.conf
A fix for https://github.com/tinode/chat/issues/755
=> Feature mongodb accept uri

.github/workflows/fix-typos.yml, INSTALL.md
This PR includes the following:
- fix typo
- adds a Github Action that automatically scans and adds a PR fixing typos
example
=> Fix typo + add Github Action that automatically fixes typos

build-all.sh
if you want to run the script under any directory...
=> GOPATH is not needed when using go-mod

server/plugins.go
should use ";" instead of ":" in comment
=> fix: wrong comment

server/cluster.go, server/db/adapter.go, server/db/mongodb/adapter.go, server/db/mysql/adapter.go, server/db/rethinkdb/adapter.go, server/main.go, server/session.go, server/store/mock_store/mock_store.go, server/store/store.go, server/tinode.conf, server/topic.go, server/user.go, server/utils.go, server/utils_test.go
Attempts to identify stale user accounts with
required unvalidated credentials and clean them up.
Note: only MySQL functionality implemented.
=> Stale unvalidated account garbage collection.

server/templ/email-password-reset-pt.templ, server/templ/email-validation-pt.templ
Added Portuguese support language.
=> Portuguese support language

server/db/adapter.go, server/db/mongodb/adapter.go, server/db/mysql/adapter.go, server/db/rethinkdb/adapter.go, server/main.go, server/store/mock_store/mock_store.go, server/store/store.go, server/tinode.conf, server/user.go
The databases would have to be updated too: the query requires new indexes. I'll update the DBs together with the change to `kvmeta`.
=> Fix deletion of unvalidated accounts

server/http.go, server/push.go, server/push/push.go, server/store/store.go, server/topic.go, server/user.go
Messages marked as read by sender must not be counted as unread. Also, exposed a bit more debug info.
=> Fix incorrect unread count in user cache.

tinode-db/main.go
Take a look here for an explanation:
https://groups.google.com/u/3/g/tinode/c/CaNtdK_fAfY
=> Fix root user handling in init-db

build-all.sh, server/db/adapter.go, server/db/mongodb/adapter.go, server/db/mysql/adapter.go, server/db/rethinkdb/adapter.go, server/store/mock_store/mock_store.go, server/store/store.go, server/topic.go
Also this https://github.com/tinode/chat/issues/842
=> Allow root to find suspended and soft-deleted topics and accounts

INSTALL.md, docker/README.md, server/db/postgres/adapter.go, server/db/postgres/blank.go, server/db/postgres/schema.sql, server/main.go, server/tinode.conf, tinode-db/README.md, tinode-db/main.go, tinode-db/tinode.conf
#232 
Added installing information.
Added PostgreSQL adapter.
Added adapter configuration in tinode.conf
=> PostgreSQL adapter

pbx/py-generate.sh, py_grpc/tinode_grpc/model_pb2.pyi
[Stub files(.pyi)](https://peps.python.org/pep-0484/#stub-files) can make users get auto-completion prompts when writing programs.
=> add a pyi file generation for tinode_grpc module

docker/README.md
change from tinode/tinode-postgresql to tinode/tinode-postgres
=> fix tinode/tinode-postgres

server/media/media.go
Ref https://github.com/tinode/chat/pull/906
=> Add CORS HTTP headers to regular (non-OPTIONS) requests

go.mod, go.sum, server/drafty/drafty.go, server/drafty/drafty_test.go
- instead of []rune, text is treated as []grapheme cluster
- added ut
=> fix: #904 drafty should correctly parse message content for push notification

README_ko.md
I really enjoyed using this project, nice work! Caught a couple of typos in the README_ko.md though 😛
=> Update README_ko.md, fix typo(s)
