INSTALL.md, server/main.go
* Added flag for server's static_data folder.
* Updated documentation to make it agnostic to the current dir.
FYI
My editor has various formatting tools for go installed, for example: goimports and golint
Which means that "on save" imports will be re-aranged to comply with go's style guide, so I advice you to install them also :)
=> Added flag for server's static_data folder to avoid copying, updated documentation

server/session.go, server/topic.go
Hello, Gene
I found 2 bugs on `filterTags()` implementation which located on `session.go`:
- `dst` param should have type `*[]string` not `[]string`, the reason is because you intend to populate `dst` with filtered tags, so the param should pass by reference, not by value.
- the value should be appended to `dst` is `s` not `parts[1]`, so for example if `s` is `"email:someone@example.com"` then the value should be appended to `dst` is `"email:someone@example.com"` not `"someone@example.com"`.
The first bug will prevent new users to add tags to its account since the resulted filtered tags would always be empty.
The consequence of second bug is obvious I think.
Thanks.
=> [Attempt to Fix Unable to Add Tags For Newly Created User]

server/db/rethinkdb/adapter.go
Hello, Gene
I found bug on `GetAuthRecord()` implementation which located on `server/db/rethinkdb/adapter.go`: 
- it’s not fetching `authLvl` field from database.
The consequence of this bug is any authenticated user will treated as unauthenticated user (`authLvl` = `0`). 
When user want to create P2P topic with another user, this will cause the permission settings for other user left unsetted (`”N”`) which will cause other user unable to do anything with the topic due to insufficient permission.
So for example if there are 2 users: `user1` with `defacs: "JWRPS"` & `user2` with `defacs: "JWRPS"` which previously do not have P2P topic between each of them. Then `user1` create P2P topic to `user2`, this will create topic which has following permission: `user1` with`acs.mode:"JWRP"` & …
=> [Attempt to Fix Unset P2P Permission for User in Other Side]

server/session.go
Hello, Gene
I found the bug. When creating the account, both `user.Access.Auth` & `user.Access.Anon` should have default access for `types.TopicCat_P2P` not `types.TopicCat_Me`.
The reason is because the `user.Access.Auth` & `user.Access.Anon` in this context is used for defining default access of current user to `P2P` topic not to `me` topic ([see here](https://github.com/tinode/chat/blob/master/API.md#acc)).
Thanks.
=> [Attempt to Fix Incorrect Acc P2P Permission's Default Value]

server/hub.go
Hello, Gene
I found that on `P2P` topic creation `recvId` & `readId` attributes on `t.perUser` is not properly initialized. This will cause `readId` to become 0 when user initially only update `recvId` using `{note}`.
Thanks
=> [Attempt to Fix Uninitialized recvId & readId in P2P Topic Creation]

server/hub.go
Hello, Gene
I found problem when shutting down system while it being hit by high traffic. It's stall, unable to finish the cleanup for topics. 
The issue is triggered by these lines: https://github.com/tinode/chat/blob/devel/server/hub.go#L207-L213. 
Notice that when we issue shutdown, apparently we didn't stop the hub for putting more topics to `hub.topics` (because we use goroutine to run `topicInit()`). So the result of `len(h.topics)` on [line 207](https://github.com/tinode/chat/blob/devel/server/hub.go#L207) could be different from the result of `len(h.topics)` on [line 211](https://github.com/tinode/chat/blob/devel/server/hub.go#L211). 
It is often that the result of `line 211` is greater than the result of `line 207` which then caused stall because `<-topicsdone` is always …
=> [Attempt to Fix Stall Shutdown]

server/hub.go
Hmmm..., I'm thinking maybe we should add checking to `h.isShutdownInProgress()` in the end of `topicInit()` as well. It's probably cleaner in terms of terminating all topics completely.
The reason is, there is still a chance that new topics would be added to `hub.topics` after call to `h.topics.Range()` is done. Even though the system won't stall because we use `topicCount` when iterating `<-topicsdone`, but the newly added topics would not be terminated cleanly, right?
But if we prevent these newly added topics from being added to `hub.topics` from the very beginning, then we could guarantee there are no additional topics being added to `hub.topics`. Hence we could make sure that all topics in `hub.topics` terminated cleanly.
What do you think?
=> [Attempt to Terminate All Topics Cleanly While Shutdown]

server/session.go
Hello, Gene
I found glitch in {hi} response. The field "params" would be still printed even if it has zero value.
For details you could take a look at this snippet which demonstrate this issue: https://play.golang.org/p/lJiwbC8Ebg
Thanks
=> Fix Params Null in Response of {hi} - Updated

server/session.go
Hello, Gene
I found glitch in `{hi}` response. The field `"params"` would be still printed even if it has zero value.
For details you could take a look at this snippet which demonstrate this issue: https://play.golang.org/p/lJiwbC8Ebg
Thanks
=> Fix Params Null in Response of {hi}

docker/chatbot/Dockerfile
:man: :bear: :pig: 
Let's make it easier to run `docker run` without having to flag `--entrypoint` to override the entry point.
=> CMD instead of ENTRYPOINT

docker/tinode/Dockerfile, docker/tinode/entrypoint.sh, docs/faq.md
It's pretty straightforward to get the bot password.
So there's no need to create another Docker image at this point.
=> In Docker image, send tinode output to stdout.

server/cluster.go, server/cluster_leader.go, server/http.go, server/hub.go, server/init_topic.go, server/main.go, server/run-cluster.sh, server/store/types/types.go, server/user.go
User cache is needed for iOS badge with the count of unread messages. It was implemented without regard for clustering. This PR adds clustering support to user cache.
=> Clustering support for user cache

server/cluster.go, server/cluster_leader.go, server/pres.go, server/session.go, server/sessionstore.go
Keep a list of remote subscriptions in sessions.
After rehashing takes place, for each session walk over the list of its remote
topic subscriptions and send {pres term} to those whose hosting nodes have changed.
=> Send {pres term} to displaced topic subs

monitoring/promexp/exporter.go
To fix "panic: inconsistent label cardinality: expected 1 label values but got 0 in []string(nil)".
=> Remove label from version metric in promexp.

server/init_topic.go, server/store/store.go, server/store/types/types.go, server/topic.go
A similar bug probably exists with `DeletedAt`.
=> touchedAt was a pointer which pointed to a shared instance of time

server/auth/basic/auth_basic.go, server/db/adapter.go, server/db/mysql/adapter.go, server/db/rethinkdb/adapter.go, server/store/store.go
There is no need in `dupe` flag if `types.ErrDuplicate` error returned when there is a duplicate
=> remove redundant 'dupe' flag

server/db/rethinkdb/adapter.go, server/store/store.go
Issue: https://github.com/tinode/chat/pull/306#issuecomment-554343709
=> move store.GetUid() from adapter to store

server/push/fcm/push_fcm.go
Needed for NotificationServiceExtension to work.
Also, enable sound on push notifications in iOS.
=> Set MutableContent and Alert field on the FCM Aps.

server/push/fcm/push_fcm.go
Needed for triggering background fetch.
=> Set content-available field in iOS push notifications.

server/cluster.go, server/datamodel.go
This fixes spurious / duplicate `{pres}` notifications when running in a cluster.
=> Pass unroutable {pres} params in intra-cluster messages

server/cluster.go, server/cluster_leader.go, server/session.go, server/sessionstore.go, server/stats.go
Changes:
1. Memory leak, line 765 in `server/cluster.go`
https://github.com/tinode/chat/compare/devel...cluster2?expand=1#diff-d412b9240514b30a308e4b4c8208ae72R765
2. Removed initialization of `Session.remoteSubs` from proxied cluster sessions because it's not used.
3. Added check for duplicate session IDs.
4. Some cosmetic changes for monitoring: version number as decimal as opposite to hex, uptime.
5. Some debug logging removed, some `Printf`s replaced with `Println`s as the latter is better performing. 
6. fixed a small memory waste in long polling. It's minor and unrelated to that massive leak.
=> Memory leak in cluster sessions, cosmetics for monitoring

server/cluster.go, server/datamodel.go, server/push/fcm/payload.go, server/session.go
The other option was to generate topic name on the session origin node then send it to the master node which is a bit more complex. I think this approach is ok while the number of nodes is not too large (~20 nodes should be fine).
=> fix for double routing of {sub topic=new} in cluster

server/cluster.go, server/hub.go, server/session.go, server/topic.go
Pass over session leave requests to the topic master and
clean up master & proxy topics (and their helper sessions) when there are no more attached sessions to them.
Note that this PR is an intermediate version. There's more work to be done to property handle subscribe/unsubscribe.
=> Topic Proxy: leave request handling

server/cluster.go, server/topic.go
Fixes for the following:
* skipSid not set on {pres} messages initiated by the master topics as a response to client requests (e.g. user A changes permissions for user B on a topic but receives pres notifications addressed to B)
* uid may be zero when processing proxy session leave requests. This updates the `Topic.perUser` map incorrectly.
=> Topic proxy: more bug fixes

server/cluster.go, server/datamodel.go, server/hub.go, server/init_topic.go, server/pbconverter.go, server/session.go, server/topic.go, server/user.go
As discussed in https://github.com/tinode/chat/pull/434
=> Rename {ClientComMessage,ServerComMessage}.from -> asUser.

server/topic.go
We thus send push notifications to all devices registered with a certain user id.
If the number of online sessions for the given uid is greater than zero,
the push notifications sent to this user's devices are marked silent.
=> Topic Proxy: Use perUser[uid].online as push.Recipient.To[uid].Delivered

server/cluster.go, server/store/store.go, server/topic.go
Background sessions are handled by the proxy topics, not master topics.
We add such sessions to the deferred notifications list at the time
when the response to the subscription request from the master is received
and count the ticks on such sessions from that point.
When a session becomes due, we poll it off the notifications list and
send the notifications request to the master (this part is a TODO -
will come in a follow up PR).
=> Proxy Topics: handling background sessions (part 1).

server/cluster.go, server/datamodel.go, server/topic.go
Add some plumbing to make sure we use the proper user id
on the when subscribing origin sessions to proxy topics (after hearing
a word about a successful subscription from the master topic).
Also, add some data structures necessary for routing deferred notifications
requests to the master.
=> Topic Proxy: deferred notifications (part 2).

server/pres.go, server/topic.go
`filter` argument in `presSubsOffline()` applies to the source topic (the topic from which the presence messages originates).
The target topics to which the message is broadcast may have different filters. Use a separate filter for it.
Example:
Publishing a message on a P2P topic sends presence message to offline users with the `R` filter (https://github.com/tinode/chat/blob/devel/server/topic.go#L340).
While the message passes the P2P topic's filtering, the target `me` topics have default `JPS` acs which the `R` filter will not pass.
=> Use separate source and target topic filters in presSubsOffline.

server/cluster.go, server/hub.go, server/session.go, server/sessionstore.go, server/topic.go
This PR repurposes the no longer used Session.remoteSubs to keep track
of the proxied uids.
Also add some cleanup to make sure perUser accounting on the master topic
remains consistent in case the node hosting the proxy topic goes down.
=> Topic Proxy: track the list of uid proxied by proxy sessions

server/hub.go
This is to handle the following situation:
upon rehasing event, the topic master moves to another node
which already hosts its proxy. The proxy needs to be shutdown.
=> On rehashing, shut down proxy topics when the master moves in.

server/cluster.go, server/datamodel.go, server/hub.go, server/init_topic.go, server/session.go, server/topic.go
* ProxyTopicData may be confused with `{data}` package. Renamed it to `ProxyTopicMessage`.
* `ProxyResponse` merged into `ClusterResponse`.
*  Removed a copy of `ClientComMessage` from `sessionOverrides`. Left only those fields which are actually used instead.
* Renamed `ClientComMessage.topic` to `.original` to disambiguate it from expanded topic name.
=> Disambiguation and flattening out data structures

server/cluster.go, server/datamodel.go, server/hub.go, server/init_topic.go, server/pbconverter.go, server/run-cluster.sh, server/session.go, server/topic.go, server/user.go
Made a bunch of fields in ClientComMessage serializable for intra-cluster communication and consequently they no longer have to be copied or inferred.
=> More disambiguation and reduced amount of copying

README_ko.md
I think the README document is something that many developers read when they first encounter this project. We made README documents in Korean to attract Korean developers. If you can't reflect this contribution, please let me know why. Thank you.
=> Translation of README Documents into Korean

server/cluster.go, server/main.go, server/session.go, server/tinode.conf, server/topic.go, server/utils.go
Parse country code from the client provided language/locale.
If it fails, fall back to the default country code specified in tinode config.
=> Pass Session.countryCode to parseSearchQuery for better rewrites.

server/topic.go
Old owner's access mode updates need to be sent to subscribers when topic's owner was changed.
=> Notify old owner's access mode updates

server/db/mongodb/adapter.go, server/db/mysql/adapter.go, server/db/rethinkdb/adapter.go
Fetching more cannot will result in overwhelming the send queues
which effectively leads to session termination.
It's one of the problems that prevented us from running valid loadtests.
=> Set defaultMaxMessageResults to 100 in DB adapters.

server/auth/basic/auth_basic.go, server/db/mysql/adapter.go
Attacker can try to send a changing password request along with the uname of another existing user.
BasicAuthenticator.UpdateRecord did not check the existing of the uname.
MySQL adapter also blindly update the record of another user to the new password.
=> Fix security flaw that attacker can change password of any user.

server/hub.go, server/session.go, server/stats.go
Latencies are defined as the time between the receipt of a client request (e.g. `{pub}`) and the moment the server replies with a `{ctrl}` to this client request.
Latencies are exported as a histogram with a predefined (hardcoded) set of buckets.
Samples are recorded upon writing out `{ctrl}` messages with the specified `Id` and `Timestamp` (expected to be the timestamp of the original client request receipt) fields.
This PR currently does not address the following issues (to be implemented in follow-up PRs & commits):
1. `Timestamp` value may not be the actual original request receipt ts (e.g. https://github.com/tinode/chat/blob/11d514b58a1b5d7a3bbc67db55fa088394c73e7c/server/hub.go#L215)
2. Latencies won't be measured correctly in the cluster mode (for requests that require …
=> Introduce histogram expvar.Var for latency tracking.

INSTALL.md
When running a standalone server, a symlink need to be created for the template directory.
=> Update install guide

server/push/fcm/payload.go, server/push/fcm/push_fcm.go, server/push/push.go, server/push/tnpg/push_tnpg.go, server/store/store.go, server/topic.go, server/user.go
Mostly done.
Missing: 
1. Subscribe/unsubscribe to FCM topics in response to changes to P permission.
~2. Send push to user's devices when the user subscribes to a channel.~ -- done
3. Allow admins to delete channel subscriptions.
4. Maybe allow admins to add users to channels, but I'm not sure. Could be too spammy.
=> Subscribing/unsubscribing to FCM topics

loadtest/tsung.xml, server/hub.go, server/session.go
Handle subscribe responses in tsung.xml in such cases.
Also, gofmt on session.go.
=> Fail subscribe requests when the Hub's join queue is full.

server/hdl_longpoll.go, server/session.go
Write loop continues to run after its host session quits. Fix it.
=> Break Session.writeLoop() in session cleanup.

server/hub.go, server/topic.go, server/topic_proxy.go
Master multiplexing sessions host multiple client sessions.
Sending a leave request w/o uid will result in dropping the whole multiplexing session.
Hence, always specify the uid.
=> Explicitly specify uid in proxy leave requests.

server/cluster.go, server/concurrency/goroutinepool.go, server/session.go, server/sessionstore.go, server/threadpool.go, server/topic.go, server/topic_proxy.go, server/user.go
This helps to limit the resources necessary to run a separate goroutine for every multiplexing session's write event loop.
=> Run topic proxy sessions' event loops on a thread pool.

server/auth/rest/auth_rest.go
Rest authenticator: in Authenticate, check if response contains a valid auth record.
=> Fix for issue 577

server/sanity-test.sh, tn-cli/tn-cli.py
The server attempts to delete the user that owns the session if the user id isn't specified in the request.
=> [tn-cli]: make 'del user' not require an explicit user id spec.

server/cluster.go, server/session.go, server/topic.go
Context: handling of cluster events.
Currently, we spawn a goroutine per master topic and multiplex proxy sessions over this goroutine using `reflect.Select`. 
This logic of using `reflect.Select` turns out to be quite pricey
in terms of both cpu and memory when the number of nodes goes up (the profile was obtained from a 5-node cluster under load).
```(pprof) top 20
Showing nodes accounting for 41800ms, 69.91% of 59790ms total
Dropped 360 nodes (cum <= 298.95ms)
Showing top 20 nodes out of 96
flat  flat%   sum%        cum   cum%
5300ms  8.86%  8.86%     7720ms 12.91%  runtime.scanobject
4250ms  7.11% 15.97%    18370ms 30.72%  runtime.mallocgc
3980ms  6.66% 22.63%     5360ms  8.96%  runtime.findObject
3860ms  6.46% 29.09%     4690ms  7.84%  runtime.heapBitsSetType
3710ms  6.21% 35.29% …
```
=> Roll back to using goroutine pool from gorountine per master topic.

server/drafty/drafty.go, server/drafty/drafty_test.go
The purpose of this change is to support pretty formatting of push notifications. Drafty `Preview()` strips all heavy entity data from content and shortens the text string. See https://github.com/tinode/chat/issues/440#issuecomment-624156909 "Push notifications" for an explanation.
=> Support for drafty push notifications

server/hdl_grpc.go, server/hdl_longpoll.go, server/hdl_websock.go, server/session.go, server/topic.go
Less blocking on the Topic.run critical path.
Move message serialization to the Session's writeLoop.
Allow batch sending of messages to the Session in order
to avoid sending messages to the Sessions' writeLoop
one by one (and thus incur synchronization costs).
=> Move some stuff off of Topic.run critical path.

README.md, server/drafty/drafty.go, server/drafty/drafty_test.go, server/pres.go, server/push/fcm/payload.go, server/push/fcm/push_fcm.go, server/push/push.go, server/topic.go
Two unrelated changes:
1. Actually sending rich push notifications using json-encoded drafty message previews (generation of them was reviewed earlier) in addition to plain text pushes.
2. Add `kp` to https://github.com/tinode/chat/pull/595. See discussion at https://github.com/tinode/chat/issues/599
=> Sending rich pushes and passing info-kp through me topic

docs/drafty.md, server/datamodel.go, server/db/mysql/adapter.go, server/hub.go, server/main.go, server/pres.go, server/topic.go, server/utils.go
* `{get sub}` did not return user's own subscription in case of channel readers (no subscriptions were returned).
* `{note what=read}` did not get stored for channel readers, so the channel always had unread messages.
* There was inconsistent checking for channel vs group topic access.
=> Channel fixes

server/push/fcm/payload.go
We must fill in aps.alert struct in order for alerts
to show up on the device.
=> Fix iOS push notifications.

server/db/adapter.go, server/db/mongodb/adapter.go, server/db/mysql/adapter.go, server/db/rethinkdb/adapter.go, server/main.go, server/stats.go, server/store/store.go, server/tinode.conf
Limiting the number of connections prevents Tinode server from overwhelming
the database. It gives Tinode server a more controlled and stable behavior.
Per http://dsas.blog.klab.org/archives/2018-02/configure-sql-db.html.
=> Mysql: limit the number of db connections.

docker/README.md
Currently the [table listing the available environment variables in the docker readme](https://github.com/tinode/chat/blob/master/docker/README.md#supported-environment-variables) is not correctly shown. This is caused by an additional newline which breaks the markdown table formatting. This simple PR removes the newline so the table is redered correctly.
=> Fix docker readme environment variables table

server/db/mysql/adapter.go, server/tinode.conf
Configure and enforce timeouts on DB queries.
This way pending queries won't have to wait and queue indefinitely long until
connection pool resources become available.
=> Mysql: query timeouts.

server/db/adapter.go, server/db/mongodb/adapter.go, server/db/mysql/adapter.go, server/db/rethinkdb/adapter.go, server/pres.go, server/store/store.go, server/topic.go, server/user.go
* Soft-deleted message records were not properly cleaned up on user and subscription deletions. The same fix as in rethink & mysql.
* Bug fixed in standalone mongo when deletions were failing with '(IllegalOperation) Transaction numbers are only allowed on a replica set member or mongos' due to `RetriableWrites` being `true` by default.
* Fix for #631 (reused slices)
* Removed unused parameters from adapter.SubsForUser (first step for #604)
=> Clean up deletions in mongodb adapter

server/topic.go, server/user.go
This eliminates an IO from the usersCache update loop.
Otherwise, we may drop updates to the usersCache because of the blocking IO calls.
This, in turn, breaks the invariants we maintain on the usersCache.
=> Make unread counter initialization in userCache non-blocking.

server/main.go, tinode-db/main.go
To make things consistent with how the server treats paths.
=> Make relative paths resolve against executable directory.

server/topic.go
We need to notify group members of a new subscription.
Presently, this is only available in p2p topic.
This is the reason why new subscriptions show up as unknown (id) in group chats in certain cases.
=> Send 'sub' push notifications when user joins a group.

server/db/mysql/adapter.go
The logic of this change is to allow browsing of subscriptions by `updatedAt` timestamp. The original change was wrong: it did not take into account that the subscription's `updatedAt` as seen by the client includes changes to the topic's or user's `updatedAt`.
This fixes just the mysql adapter. The other two have to be fixed too.
=> Fix 'me' subs

server/cluster.go, server/datamodel.go, server/hub.go, server/init_topic.go, server/session.go, server/session_test.go, server/store/mock_store/mock_store.go, server/topic.go, server/topic_proxy.go, server/topic_test.go
`ClientComMessage` has a `Session` field now. The wrappers are obsolete now.
=> Got rid of sessionJoin and sessionLeave wrappers

server/auth/basic/auth_basic.go, server/db/mysql/schema.sql, server/drafty/drafty.go, server/drafty/drafty_test.go, server/push/fcm/payload.go, server/store/store.go
Drafty formatting refactored to use trees: a doc is converted to a tree where each node is uniformly formatted, like
[_quick **fox** jumps_ over] ->
```
[[EM: quick, [ST: fox], jumps], over]
```
It simplified removal of quoted text, shortening etc. Also added a few more tests for various corner cases.
--
There are three unrelated changes:
* `auth_basic.go`: added '**.**' as a permitted character to logins: https://groups.google.com/g/tinode/c/Ncl0MG-QzQM/m/cvi88V0ACAAJ
* Added a comment to mysql `schema.sql` as a reaction to this: https://groups.google.com/g/tinode/c/meEqSq6XzKU/m/tzGrao6-CAAJ
* Fixed a bug in `store.go` related to handling of out-of-band uploaded files.
=> Drafty handling refactored to use trees

server/db/mysql/adapter.go
`err` being nil causes the rollback to be skipped
=> mysql-adapter: fix deadlock in SubsDelete if record is not found

server/cluster.go, server/init_topic.go, server/session.go, server/topic_proxy.go
```
I2021/11/19 13:10:13 in: '{"sub":{"id":"95264","topic":"fnd","get":{"what":"sub"}}}' sid='RxIw50I5tpQ' uid='PFAQXh91150'
W2021/11/19 13:10:13 cluster: call failed tinode-2 unexpected EOF
W2021/11/19 13:10:13 proxy topic: route sess update request from proxy to master failed: unexpected EOF
I2021/11/19 13:10:14 cluster: connected to tinode-2
panic: sync: negative WaitGroup counter
goroutine 36840 [running]:
sync.(*WaitGroup).Add(0xc000480300, 0xc0004ce1a0)
/usr/local/go/src/sync/waitgroup.go:74 +0x105
sync.(*WaitGroup).Done(...)
/usr/local/go/src/sync/waitgroup.go:99
main.(*Topic).runProxy(0xc000480300, 0xc000cb9950)
/Users/gene/go/src/github.com/tinode/chat/server/topic_proxy.go:41 +0x636
main.(*Topic).run(0xc0003fdad0, 0xc000cb9950) …
```
=> Possible fix for a crash

server/push/common/typedef.go, server/push/fcm/payload.go, server/push/fcm/push_fcm.go, server/push/tnpg/push_tnpg.go
TNPG updated
FCM push refactored a bit to use the new error handling. 
Common code moved to a separate package.
All pushes seem to work, including voip. But voip pushes arrive as normal pushes as opposite to PushKit despite the fact that they are sent as voip.
=> TNPG updated to work with FCM push v1.

server/topic_test.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
https://pkg.go.dev/testing#T.Fatal 
> Fatal is equivalent to Log followed by FailNow.
so `break` will not run.
=> delete minor unreachable code caused by t.Fatal

server/cluster.go, server/topic.go
Multiplexing sessions are currently attached to topic masters with `isChanSub` set to false.
This leads to errors in handling channel requests routed from proxies.
Solution:
For channel topics, add two multiplexing sessions depending on request type: regular "grpXXX-node" and "chnXXX-node" with `isChanSub` set to true.
=> Add chn multiplexing sessions to topic master.

server/cluster.go, server/pres.go, server/topic.go, server/topic_proxy.go
Errors fixed:
1. When both `chnX` and `grpX` multiplexing sessions (for the same channel topic) are attached to topic master, send messages to only `grpX`.
2. When rewriting topic name for the client (`Topic.maybeFixTopicName()`) take subscription type (channel/non-channel) into account.
3. Set `Original` field in the `leave` messages from topic proxy to master so the master can process these requests correctly.
=> More correct handling of channel topics in cluster mode

server/cluster.go, server/datamodel.go, server/run-cluster.sh, server/session.go, server/topic_proxy.go
1. Added a network connection timeout when connecting to nodes.
2. Added a channel+goroutine and a check for overload for RPC calls from Proxy to Master. Proxy topic sends a message to clients if RCP call to master failed. 
3. Added a check for overload when master node sends requests to master's hub.
What I don't like here is that when the master rejects a call from the proxy, the error is just logged by the `p2mSenderLoop`, while it should be reported back to the calling session. It's highly unlikely that this would happen in production because the buffer cluster->hub at master is much bigger than the buffer at proxy->master. But still.
=> Remove deadlock on server overload, #786

tinode-db/gendb.go
When use `./init-db -data=mydata.json`, It seems that the program ignores the input tags. #795 
I dont programmer of *GO* but I think that is fixed. *Please review it*
=> Fix Bug: When Init-DB by json file, ignore tags of user if defined (Issue #795)

tn-cli/tn-cli.py
Fixes "resolve" and "pub" commands in CLI.
Examples of wrong behaviour before fix:
**pub**:
**resolve**:
=> fix: add quotes to str in tn-cli : encode_to_bytes

server/store/types/types.go, server/topic.go
Fixes the following bug:
1. Bob is online (does not matter how).
2. Alice is online from both web and Android. Alice sees Bob as online, everything is fine.
3. Alice disconnects Android, then reconnects, web stays connected. Now Alice sees Bob as offline on Android.
=> Fix online status of unchanged online connections

loadtest/tinode.scala, server/session.go, server/sessionstore.go, server/topic.go, server/topic_proxy.go
1. Session.addSub & Session.delSub should be happening (atomically) together modifications of Topic.sessions.
2. Only one of Session.subscribe() and Session.leave() is allowed to be inflight at any given moment.
Attempt at addressing https://github.com/tinode/chat/issues/866
=> Fix a race condition around Session.subs.

chatbot/python/.gitignore, chatbot/python/chatbot.py
Hi,
Thanks for your great project. I am working on deploying Tinode and developing chatbots. The `botUID` in the current chatbot example does not work because it is always `None`. So this PR fixes it.
By the way, I can help build a unified Python API for both chatbot and tn-cli, based on the code of tn-cli. What is your opinion on this? Thank you!
=> Fix botUID in chatbot

go.mod, server/linkpreview.go, server/main.go, server/session.go, server/tinode.conf
=> feat: add link-preview handler
